include:
  - project: kount/third_party/tpa-ci-shared
    file:
        - base/sq-scan.yml
        - core/rules.yml
        - version.yml
    ref: 2.5.3

stages:
  - version
  - build
  - test
  - sonarqube scan
  - deploy

.dotnet:
  image: mcr.microsoft.com/dotnet/sdk:5.0
   
build:
  stage: build
  extends: .dotnet
  script:
    - dotnet build 
    
test:
 stage: test
 extends: .dotnet
 script:
   - dotnet test "KountRisTest"

test config:
 stage: test
 extends: .dotnet
 script:
   - dotnet test "KountRisConfigTest"

sonarqube scan:
  extends: .sq-scan
  stage: sonarqube scan
  variables:
    SRC_INCLUSIONS: "**/*.cs"
    SRC_EXCLUSIONS: "**/bin/**,**/obj/**,**/DS_Store/**,**/.git/**,**/*.vs,**/*_site,**/*articles,**/*.gitignore,**/*.key,**/*.yml"

nuget deploy:
  stage: deploy
  extends: .dotnet
  only:
    - tags
  script:
    - apt-get update -qq
    # BUILD_VERSION is cut to 17 characters so SDK_VERSION will not exceed 32 characters in total
    - SDK_VERSION=`echo $BUILD_VERSION | cut -c-17`
    - echo ${SDK_VERSION}
    - |
      if [ ${SDK_VERSION} ]
      then
        echo "sed -i \"s/0.0.0/${SDK_VERSION}/g\" ${CI_PROJECT_DIR}/SDK/Kount/Ris/Config.cs"
        sed -i "s/0.0.0/${SDK_VERSION}/g" ${CI_PROJECT_DIR}/SDK/Kount/Ris/Config.cs
        echo "sed -i \"s/0.0.0/${SDK_VERSION}/g\" ${CI_PROJECT_DIR}/SDK/KountRisSdk.csproj"
        sed -i "s/0.0.0/${SDK_VERSION}/g" ${CI_PROJECT_DIR}/SDK/KountRisSdk.csproj
        echo "sed -i \"s/0.0.0/${SDK_VERSION}/g\" ${CI_PROJECT_DIR}/README.md"
        sed -i "s/0.0.0/${SDK_VERSION}/g" ${CI_PROJECT_DIR}/README.md
        cat ${CI_PROJECT_DIR}/SDK/Kount/Ris/Config.cs
        cat ${CI_PROJECT_DIR}/SDK/KountRisSdk.csproj
        cat ${CI_PROJECT_DIR}/README.md
      fi
    - dotnet build
    - PKGPATH=$(find /builds/kount/third_party/kount-ris-dotnet-sdk/SDK/bin/Debug/*.nupkg)
    - echo $PKGPATH
    - dotnet nuget push $PKGPATH --source https://www.nuget.org/ -k $NUGET_API_KEY


