include:
  - project: kount/third_party/tpa-ci-shared
    file:
        - base/sq-scan.yml
        - core/rules.yml
        - version.yml
    ref: 2.5.3

stages:
  - version
  - build
  - test
  - sonarqube scan
  - deploy

.dotnet:
  image: mcr.microsoft.com/dotnet/sdk:5.0
   
build:
  stage: build
  extends: .dotnet
  script:
    - dotnet build 
    
test:
 stage: test
 extends: .dotnet
 script:
   - dotnet test "KountRisTest"

test config:
 stage: test
 extends: .dotnet
 script:
   - dotnet test "KountRisConfigTest"

sonarqube scan:
  extends: .sq-scan
  stage: sonarqube scan
  variables:
    SRC_EXCLUSIONS: "**/bin/**,**/obj/**,**/DS_Store/**,**/.git/**,**/*.vs,**/*_site,**/*articles,**/*.gitignore,**/*.key,**/*.yml"

nuget deploy:
  stage: deploy
  extends: .dotnet
  only:
    - tags
  script:
    - dotnet build
    - apt-get update -qq
    - BUILD_VERSION= ${BUILD_VERSION} || true
    - BUILD_VERSION=`echo $BUILD_VERSION | cut -c-17`
    - SDK_VERSION=${BUILD_VERSION}
    - echo ${SDK_VERSION}
    - |
      if [ -n "${BUILD_VERSION}" ]
      then
        # BUILD_VERSION is cut to 17 characters so SDK_VERSION will not exceed 32 characters in total
        BUILD_VERSION=`echo $BUILD_VERSION | cut -c-17`
        echo "sed -i \"s/0.0.0/${BUILD_VERSION}/g\" ${CI_PROJECT_DIR}/SDK/Kount/Ris/Config.cs"
        sed -i "s/0.0.0/${BUILD_VERSION}/g" ${CI_PROJECT_DIR}/SDK/Kount/Ris/Config.cs
        cat ${CI_PROJECT_DIR}/SDK/Kount/Ris/Config.cs
      fi
    - PKGPATH=$(find /builds/kount/third_party/kount-ris-dotnet-sdk/SDK/bin/Debug/*.nupkg)
    - echo $PKGPATH
    - dotnet nuget push $PKGPATH --source https://www.nuget.org/ -k $NUGET_API_KEY
    # let's deploy locally as well, just to have a copy in gitlab
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push $PKGPATH --source gitlab


